<?php
/**
 * @file
 * ftw_text_blocks.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function ftw_text_blocks_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['block-count_incorrect_reports'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_incorrect_reports',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_owners_acknowledged'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_owners_acknowledged',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_owners_fixed'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_owners_fixed',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_owners_informed'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_owners_informed',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_reporters'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_reporters',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_reports_in_progress'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_reports_in_progress',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_tweets'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_tweets',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_volunteers'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_volunteers',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-count_websites_reported'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'count_websites_reported',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'stats',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-email_not_an_acessibility_email'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_not_an_acessibility_email',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Warning, you may be blocked from reporting to Fix the Web',
    'visibility' => 0,
  );

  $export['block-email_not_an_acessibility_email2'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_not_an_acessibility_email2',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Sorry, But you have been blocked from reporting to Fix the Web',
    'visibility' => 0,
  );

  $export['block-email_report_closure_to_reporter'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_report_closure_to_reporter',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Fix the Web: Your report has been dealt with',
    'visibility' => 0,
  );

  $export['block-email_spam_body'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_spam_body',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Sorry, But you have been blocked from reporting to Fix the Web',
    'visibility' => 0,
  );

  $export['block-email_volunteer_nag_email'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_volunteer_nag_email',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Fix the web dashboard nudge',
    'visibility' => 0,
  );

  $export['block-email_volunteer_subject'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_volunteer_subject',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-email_web_owner'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'email_web_owner',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Fix the web needs your help!',
    'visibility' => 0,
  );

  $export['block-help_accept_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_accept_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/accept',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -22,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_assign_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_assign_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/assign/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_close_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_close_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/close',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_dashboard'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_dashboard',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -25,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_dashboard_closed_reports'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_dashboard_closed_reports',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/closed',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -24,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_internal_email'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_internal_email',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/user/*/email/report/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_post_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_post_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/post',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_process_reports'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_process_reports',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/process',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_relist_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_relist_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/relist',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_simmilar_reports'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_simmilar_reports',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/similar',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_volunteer_question'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_volunteer_question',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/user/*/email/report/*/similar',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-help_waiting_reports'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'help_waiting_reports',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/waiting',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'help_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -23,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_accept_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_accept_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/accept',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -24,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_assign_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_assign_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/assign/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_close_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_close_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/close',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_dashboard'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_dashboard',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -25,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_delete_account'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_delete_account',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-intro_downgrade_volunteer'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_downgrade_volunteer',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['block-intro_internal_email'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_internal_email',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/user/*/email/report/*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_post_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_post_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/post',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_process_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_process_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/process',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_relist_report'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_relist_report',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/relist',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_simmilar_reports'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_simmilar_reports',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/report/*/similar',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => -23,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_user_registration'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_user_registration',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'register/reporter',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-intro_volunteer_question'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'intro_volunteer_question',
    'module' => 'block',
    'node_types' => array(),
    'pages' => 'dashboard/user/*/email/report/*/similar',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => 'intro_content',
        'status' => 1,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['block-tweet_report_closure'] = array(
    'cache' => -1,
    'custom' => 0,
    'machine_name' => 'tweet_report_closure',
    'module' => 'block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'ftw' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ftw',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
